items/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from items.views import ProductListView, DetailView, ProductDetailView, SupplierListView, SupplierDetailView, \
    actionview, CustomerListView, CustomerDetailView, objectsalesview, ProductCategoryListView, \
    ProductCategoryDetailView, ProductSubCategoryListView, objectforecastview, ProductSubCategoryDetailView, \
    ImportProducts, UpdateAttributes, SettingsView, \
    UpdateForecast, Optimize
from django.views import static

app_name = 'items'
urlpatterns = [
    path('items/', ProductListView.as_view(), name='Products'),
    path('items/<int:pk>/details/', ProductDetailView.as_view(), name='Product Details'),
    path('items/<int:pk>/', ProductDetailView.as_view()),
    path('suppliers/', SupplierListView.as_view(), name='Suppliers'),
    path('customers/', CustomerListView.as_view(), name='Customers'),
    path('action/', actionview, name='Action'),
    path('itemcategories/', ProductCategoryListView.as_view(), name='Product Categories'),
    path('itemcategories/<int:pk>/details/', ProductCategoryDetailView.as_view(), name='Product Categories Details'),
    path('itemcategories/<int:pk>/', ProductCategoryDetailView.as_view()),
    path('itemsubcategories/', ProductSubCategoryListView.as_view(), name='Product SubCategories'),
    path('itemsubcategories/<int:pk>/details/', ProductSubCategoryDetailView.as_view(), name='Product SubCategory Details'),
    path('itemsubcategories/<int:pk>/', ProductSubCategoryDetailView.as_view()),
    path('suppliers/<int:pk>/details/', SupplierDetailView.as_view(), name='Supplier Details'),
    path('suppliers/<int:pk>/', SupplierDetailView.as_view()),
    path('customers/<int:pk>/details/', CustomerDetailView.as_view(), name='Customer Details'),
    path('customers/<int:pk>/sales/', objectsalesview, name='Customer Sales Analysis'),
    path('suppliers/<int:pk>/sales/', objectsalesview, name='Supplier Sales Analysis'),
    path('itemsubcategories/<int:pk>/sales/', objectsalesview, name='Product SubCategory Sales Analysis'),
    path('items/<int:pk>/sales/', objectsalesview, name='Product Sales Analysis'),
    path('suppliers/<int:pk>/forecast/', objectforecastview, name='Supplier Forecast'),
    path('customers/<int:pk>/forecast/', objectforecastview, name='Customer Forecast'),
    path('itemsubcategories/<int:pk>/forecast/', objectforecastview, name='Product SubCategory Forecast'),
    path('items/<int:pk>/forecast/', objectforecastview, name='Product Forecast'),
    path('customers/<int:pk>/', CustomerDetailView.as_view()),
    path('settings/', SettingsView, name='Settings'),
    path('settings/importproducts/',ImportProducts, name='Import'),
    path('settings/updateattributes/',UpdateAttributes, name='Update'),
    path('settings/updateforecast/',UpdateForecast, name='updateforecast'),
    path('settings/optimize/',Optimize, name='Optimize'),
]

re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable

test2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views import static
from django.urls import re_path, include


urlpatterns = [
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
    path('celery-progress/',include('celery_progress.urls', namespace='celery_progress'))
]
#re_path(r'^celery-progress/', include('celery_progress.urls', namespace='celery_progress')),  # the endpoint is configurable
#path('', include(('celery_progress.urls', 'home'), namespace='home'))
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

items/forms.py
import django.forms as forms
from crispy_forms.layout import Submit, Layout, Div, Row
from django.forms import Form
from crispy_forms.helper import FormHelper
from .models import Itemtrans, ProductDetail, OptimizationItemAttribute, OptimizationItem, Settings
import items.models as mod


class SupplierForm(forms.Form):
    like_website = forms.TypedChoiceField(
            label = "Do you like this website?",
            choices = ((1, "Yes"), (0, "No")),
            coerce = lambda x: bool(int(x)),
            widget = forms.RadioSelect,
            initial = '1',
            required = True,
        )
    moretxt = forms.CharField(label = "Anything else?",
                              required = True)

    def __init__(self, *args, **kwargs):
        super(SupplierForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'get'
        self.helper.form_action = 'submit_survey'

class ProductForm(forms.Form):
    code = ProductDetail.code
    name = ProductDetail.name

    def __init__(self, *args, **kwargs):
        super(SupplierForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'get'
        self.helper.form_action = 'submit_survey'


class ImportProductForm(forms.Form):
    code = ProductDetail.code


class SettingsForm(forms.ModelForm):
    A_percent=Settings.A_percent
    B_percent=Settings.B_percent
    C_percent=Settings.C_percent

    def __init__(self, *args, **kwargs):
        super(SettingsForm, self).__init__(*args, **kwargs)
       # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
       # You can dynamically adjust your layout
        self.helper.layout = Layout(
            Row(
                Div('A_percent', css_class='col-sm-1', ),
                Div('B_percent', css_class='col-sm-1', ),
                Div('C_percent', css_class='col-sm-1', ),
                css_class='row',
            ))

    class Meta:
        model = Settings
        fields = {'A_percent','B_percent', 'C_percent'}

items/views.py
import json
from django.db.models import F, Sum, FloatField, Case, When, Value, CharField, DecimalField, IntegerField, Avg, OuterRef, Subquery
from django.db.models.functions import Left
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.generic import UpdateView, DetailView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
import datetime
from items.forms import SupplierForm, ImportProductForm, SettingsForm
from items.models import ProductFilter, SupplierFilter, SuppBalance, ProductCategoryFilter, ProductSubCategory,  CeleryTasks
from items.tables import ProductTable, SupplierTable,ProductCategoryTable,ProductSubCategoryListTable
from .functions import sales_plot, gauge_plot, sunburst_plot, plotly_table, objforecast_plot, dist_plot
from .models import Itemtrans, ProductDetail, Product, Supplier, SupplierDetail, Customer, CustomerDetail, \
    CustomerFilter, ItemFinData,ProductCategory, ProductSubcategoryFilter, ProductSubCategoryList, OptimizationItem, OptimizationItemAttribute, Settings, \
    SupplierCategory, FullItemStoreData
from dateutil.relativedelta import relativedelta
from items.tasks import missing_items, update_atributes, forecast, optimize
import pandas as pd


# Create your views here.

def SettingsView(request):
    template_name = "settings.html"
    context = {}
    if request.method == "GET":
        pending_task=False
        if CeleryTasks.objects.filter(status='PROGRESS'):
            pending_task=True
        queryset = Settings.objects.get(pk=1)
        context = {'pending_task': pending_task, 'QuerySet': queryset }
        return render(request, template_name, context)
    elif request.method == "POST":
        content = json.loads(request.body)
        try:
            g = Settings.objects.get(pk=1)
            g.A_percent = content["A_percent"]
            g.B_percent = content["B_percent"]
            g.C_percent = content["C_percent"]
            g.save()
            context = {'success': True}
        except:
            context = {'success': False}
        finally:
            return render(request, template_name, context)


def actionview(request):
    template_name = "action.html"
    form_class = SupplierForm
    context = {'form': form_class}
    return render(request, template_name, context)


def ImportProducts(request):
    if request.method == 'GET':
        result = missing_items.delay()
        data = {
            'task_id': result.task_id
        }
        return HttpResponse(json.dumps({"task_id": result.task_id}),content_type="application/json")
        #return render(request, 'action.html', context={'task_id': result.task_id, 'form': ImportProductForm})
    else:
        return HttpResponse("Request method is not a GET")


def UpdateAttributes(request):
    if request.method == 'GET':
        result = update_atributes.delay()
        data = {
            'task_id': result.task_id
        }
        return HttpResponse(json.dumps({"task_id": result.task_id}),content_type="application/json")
        #return render(request, 'action.html', context={'task_id': result.task_id, 'form': ImportProductForm})
    else:
        return HttpResponse("Request method is not a GET")


def UpdateForecast(request):
    if request.method == 'GET':
        result = forecast.delay()
        data = {
            'task_id': result.task_id
        }
        return HttpResponse(json.dumps({"task_id": result.task_id}),content_type="application/json")
        #return render(request, 'action.html', context={'task_id': result.task_id, 'form': ImportProductForm})
    else:
        return HttpResponse("Request method is not a GET")

def Optimize(request):
    if request.method == 'GET':
        result = optimize.delay()
        data = {
            'task_id': result.task_id
        }
        return HttpResponse(json.dumps({"task_id": result.task_id}),content_type="application/json")
        #return render(request, 'action.html', context={'task_id': result.task_id, 'form': ImportProductForm})
    else:
        return HttpResponse("Request method is not a GET")


class ProductListView(SingleTableMixin, FilterView):
    table_class = ProductTable
    queryset = Product.objects.all().order_by('-valuey0')
    template_name = "index.html"
    filterset_class = ProductFilter


class ProductCategoryListView(SingleTableMixin, FilterView):
    template_name = "index.html"
    table_class = ProductCategoryTable
    filterset_class = ProductCategoryFilter
    #filterset_class = ProductCategoryFilter

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data(**kwargs)
        queryset = ProductCategory.objects.all().order_by('-valuey0')
        context['table'] = ProductCategoryTable(queryset)
        return context


class ProductSubCategoryListView(SingleTableMixin, FilterView):
    template_name = "index.html"
    queryset = ProductSubCategoryList.objects.all().order_by('-valuey0')
    table_class = ProductSubCategoryListTable
    filterset_class = ProductSubcategoryFilter
    #filterset_class = ProductCategoryFilter


class SupplierListView(SingleTableMixin, FilterView):
    table_class = SupplierTable
    queryset = Supplier.objects.all().order_by('-valuey0')
    template_name = "index.html"
    filterset_class = SupplierFilter


class CustomerListView(SingleTableMixin, FilterView):
    table_class = SupplierTable
    queryset = Customer.objects.all().order_by('-valuey0')
    template_name = "index.html"
    filterset_class = CustomerFilter


class ProductDetailView(DetailView):
    model = ProductDetail
    fields = [field.name for field in ProductDetail._meta.concrete_fields]
    template_name = "details.html"

    def get_queryset(self):
        return ProductDetail.objects.filter(id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['fields'] = self.fields
        td = datetime.datetime(2020,12,31) - relativedelta(months=+1) #datetime.datetime(2020,12,31).month
        value_gauge_data = Itemtrans.objects.filter(iteid=self.kwargs['pk'], source=5, fipid__lt=td.month).values('iteid','fyeid').annotate(value=Sum(F('trnvalue') * F('outputvalmode'), output_field=FloatField())).order_by('-fyeid')
        div = gauge_plot(value_gauge_data,"Sales Value Jan-"+td.strftime("%b")+" ("+str(datetime.datetime(2020,12,31).year-1)+"-"+str(datetime.datetime(2020,12,31).year)+")")
        value_gauge2_data = Itemtrans.objects.filter(iteid=self.kwargs['pk'], source=5, fipid__lt=td.month).values('iteid', 'fyeid').annotate(
            value=Sum(F('primaryqty') * F('outputquantmode'), output_field=FloatField())).order_by('-fyeid')
        div2 = gauge_plot(value_gauge2_data, "Sales Units Jan-"+td.strftime("%b")+" ("+str(datetime.datetime(2020,12,31).year-1)+"-"+str(datetime.datetime(2020,12,31).year)+")")
        #value1_gauge2_data = Itemtrans.objects.filter(iteid=self.kwargs['pk'], fyeid=datetime.datetime(2020,12,31).year, fipid__lte=datetime.datetime(2020,12,31).month).values('iteid').annotate(value=Sum(F('trnvalue') * F('outputvalmode'), output_field=FloatField()))
       # value2_gauge2_data = Itemtrans.objects.filter(iteid=self.kwargs['pk'], fyeid=datetime.datetime(2020,12,31).year-1, fipid__lte=datetime.datetime(2020,12,31).month).values('iteid').annotate(value=Sum(F('trnvalue') * F('outputvalmode'), output_field=FloatField()))
        #div2 = gauge_plot(value1_gauge2_data,"  ")
        context['graph'] = div
        context['graph2'] = div2
        v=value_gauge_data[0].get('value')/value_gauge2_data[0].get('value')
        context['field1'] = v
        c=ItemFinData.objects.filter(masterid=self.kwargs['pk']).values('costvalue')[0].get('costvalue') #datetime.datetime(2020,12,31).year
        d1 = list(Itemtrans.objects.select_related().filter(iteid=self.kwargs['pk'], source=5, fyeid=td.year).values(
            'perid__code', 'fyeid', 'perid__name'). \
            annotate(value=Sum(F('trnvalue') * F('outputvalmode'), output_field=FloatField()),
                     domorex=Case(When(perid__code__startswith='8', then=Value('export'))
                                  , default=Value('domestic'), output_field=CharField())).order_by('-fyeid'))
        div3=sunburst_plot(d1, 'test')                           #datetime.datetime(2020,12,31).month
        d = list(Itemtrans.objects.all().filter(iteid=self.kwargs['pk'], source=5, fipid__lt=td.month).values('fyeid').annotate(
            value=Sum(F('trnvalue') * F('outputvalmode'), output_field=IntegerField())).order_by('fyeid'))

        for i in d:
            if d.index(i) == 0:
                i['yoy'] = str("-%")
                i['color']=('rgb(255,255,255)')
                continue
            else:
                i['yoy'] = ((i['value'] / d[d.index(i) - 1]['value']) - 1)*100
                if i['yoy']>0:
                    i['color']='rgb(152,251,152)'
                else:
                    i['color']='rgb(255,99,71)'
                i['yoy']=str(int(round(i['yoy'])))+"%"
        div4=plotly_table(d)
        context['graph4'] = div4
        context['graph3'] = div3
        context['field2'] = v-c
        context['field22'] = (1-(c/v))*100
        # context['panel'] = acp[0] + acp[1]
        return context


class ProductSubCategoryDetailView(DetailView):
    model = ProductSubCategory
    fields = [field.name for field in ProductSubCategory._meta.concrete_fields]
    fields.extend([field.name for field in OptimizationItem._meta.concrete_fields])
    fields.extend([field.name for field in FullItemStoreData._meta.concrete_fields])
    template_name = "details.html"

    def get_queryset(self):
        return ProductSubCategory.objects.filter(id=self.kwargs['pk']).values('id','name','optimizationitem__annual_consumption_value',

items/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
       <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    SalesInsight
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
{#             <li class="nav-item active">#}
{#        <a class="nav-link" href="\items\">Είδη <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="\\">Link</a>#}
{#      </li>#}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'items:Product Categories' %}">Categories</a>
            <a class="dropdown-item" href="{% url 'items:Product SubCategories' %}">Subcategories</a>
          <a class="dropdown-item" href="{% url 'items:Products' %}">Specific items</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">Συνολική αναφορά πωλήσεων</a>
            <a class="dropdown-item" href="{% url 'items:Action' %}">Action</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Suppliers
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Categories</a>
          <a class="dropdown-item" href="{% url 'items:Suppliers' %}">List</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">Συνολική αναφορά πωλήσεων</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Customers
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Categories</a>
          <a class="dropdown-item" href="{% url 'items:Customers' %}">List</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">Συνολική αναφορά πωλήσεων</a>
        </div>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Configuration
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'items:Settings' %}">Settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">About</a>

        </div>
      </li>
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#">Disabled</a>#}
{#      </li>#}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

        <title>GRANTEX TEST APP</title>
{#        <link rel="stylesheet" type="text/css" href="{% static 'items/bootstrap.css' %}">#}
        {% block extrahead %}{% endblock %}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "items/bootstrap/css/bootstrap.css" %}">
    <!-- Compiled and minified JavaScript for Materialize CSS -->
<script   src="https://code.jquery.com/jquery-3.5.1.js"   integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "items/csrf.js" %}"></script>
    <script src="{% static "items/bootstrap/js/bootstrap.js"  %}"></script>
    </head>
    <body>

         {% block body %}{% endblock %}

    </body>
</html>

items/templates/checkbox_example.html
{% extends 'bootstrap_template.html' %}
{% load bootstrap3 %}

{% block title %}django-tables2 <code>CheckBoxColumn</code> example{% endblock %}
{% block body %}
{{ block.super }}

{% bootstrap_javascript jquery=True %}
<script>
$(function () {

    // calculate the sum of the population column for the selected rows.
    function update_sum() {
        var sum = 0;
        $('tbody input[type=checkbox]').each(function () {
            if ($(this).is(':checked')) {
                sum += parseInt($(this).parents('tr').find('.population').html());
            }
        });

        $('tfoot .population').html(sum);
    }

    // update the sum after each change
    $('tbody input[type=checkbox]').on('change', update_sum);

    // update the sum initially.
    update_sum();
});
</script>
{% endblock %}

items/templates/country_detail.html
{% extends 'semantic_template.html' %}
{% load django_tables2 %}

{% block body %}
<h1>{{ country }}</h1>

<h2>Persons in this country</h2>
{% render_table table 'django_tables2/semantic.html' %}
{% endblock %}

items/templates/details_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block body %}
<body>
<div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Επιλογές</div>
      <div class="list-group list-group-flush">
          {% if "suppliers" in request.path %}
                  <a href="{% url 'items:Supplier Details' object.id %}" class="list-group-item list-group-item-action bg-light">Basic details</a>
                 <a href="{% url 'items:Supplier Sales Analysis' object.id %}" class="list-group-item list-group-item-action bg-light">Sales analysis</a>
                <a href="{% url 'items:Supplier Forecast' object.id %}" class="list-group-item list-group-item-action bg-light">Forecasting</a>
          {% elif "customers" in request.path  %}
                <a href="{% url 'items:Customer Details' object.id %}" class="list-group-item list-group-item-action bg-light">Basic details</a>
                 <a href="{% url 'items:Customer Sales Analysis' object.id %}" class="list-group-item list-group-item-action bg-light">Sales analysis</a>
                <a href="{% url 'items:Customer Forecast' object.id %}" class="list-group-item list-group-item-action bg-light">Forecasting</a>
          {% elif "itemcategories" in request.path  %}
                <a href="{% url 'items:Product Categories Details' object.category %}" class="list-group-item list-group-item-action bg-light">Basic details</a>
          {% elif "itemsubcategories" in request.path  %}
                <a href="{% url 'items:Product SubCategory Details' object.id %}" class="list-group-item list-group-item-action bg-light">Basic details</a>
                 <a href="{% url 'items:Product SubCategory Sales Analysis' object.id %}" class="list-group-item list-group-item-action bg-light">Sales analysis</a>
                <a href="{% url 'items:Product SubCategory Forecast' object.id %}" class="list-group-item list-group-item-action bg-light">Forecasting</a>
          {% else %}
                 <a href="{% url 'items:Product Details' object.id %}" class="list-group-item list-group-item-action bg-light">Basic details</a>
                 <a href="{% url 'items:Product Sales Analysis' object.id %}" class="list-group-item list-group-item-action bg-light">Sales analysis</a>
                <a href="{% url 'items:Product Forecast' object.id %}" class="list-group-item list-group-item-action bg-light">Forecasting</a>
          {% endif %}
      </div>
    </div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <button class="btn btn-outline-success my-2 my-sm-0" id="menu-toggle">Απόκρυψη επιλογών</button>
             {% block body2 %}{% endblock %}
    </div>
    <!-- /#page-content-wrapper -->

  </div>
<script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
      if($(this).text().trim() == 'Εμφάνιση επιλογών'){
          $(this).text('Απόκρυψη επιλογών');
      }else{
          $(this).text('Εμφάνιση επιλογών');
      }
    });
</script>


</body>
{% endblock %}

items/templates/extended_table.html
{% extends "django_tables2/table.html" %}

{% block table.tfoot %}
<tfoot>
    <tr>
        <td colspan="{{ table.columns|length }}">This is a footer</td>
    </tr>
</tfoot>
{% endblock %}

items/templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load django_tables2 %}
{% load static %}
{% load i18n %}
{% block body %}
<body>
    <div class="container">
    {% if filter.base_filters|length > 0 %}
        <form action="" method="get" id="form_login" class="form-inline">
            {{ filter.form|crispy }}
            <button type="filter">Filter</button>
        </form>
    {% endif %}
    {% render_table table %}
    </div>
</body>
{% endblock %}

items/templates/multiTable.html
{% extends "base.html" %}
{% load django_tables2 %}
{% load static %}

{% block extrahead %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <link href="{% static 'django_tables2/bootstrap.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="container">

        <h1>Multiple tables on a single page using MultiTableMixin</h1>

        <p>
            Pagination should work independently for each table,
            the second table excludes the column 'country'.
        </p>
        <div class="row">
            {% for table in tables %}
                <div class="col-lg-12">{% render_table table %}</div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

items/templates/person_detail.html
{% extends 'semantic_template.html' %}
{% load django_tables2 %}

{% block body %}
<h1>{{ person }}</h1>

country: <a href="{{ person.country.get_absolute_url }}">{{ person.country }}</a>
{% endblock %}

items/templates/semantic_template.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
<head>
    <title>django_tables2 with semantic template example</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.css">
</head>
<body>
    <div class="ui container">
        {% block body %}
        <h3>django_tables2 with Semantic UI template example</h3>
        {% render_table table %}
        {% endblock %}
    </div>
</body>
</html>

items/templates/tutorial.html
{% load django_tables2 %}
{% load static %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
    </head>
    <body>
        <h3>django_tables2 with the default template example</h3>

        {% render_table table %}
    </body>
</html>